prefer_small_ascii = true
spacing = 2
padding = 0
separator = "..."
key_color = "green"
separator_color = "yellow"

[box.inner_margin]
x = 2
y = 1

[custom_ascii]
color = "yellow"

[keys]
host = "host"
kernel = "kernel"
distro = "os"
wm = "wm"
shell = "shell"
packages = "pkgs"
uptime = "uptime"
