right_format = '$cmd_duration'
# add_newline = true

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'
style = 'bold yellow'

[directory]
style = 'bold blue'
truncation_symbol = '.../'

[git_branch]
# style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'
